//
//  CreateUserRequest.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:15:33 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "first_name" : "job",
  "last_name" : "lebre",
  "email" : "joblebre@maca.jp"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface CreateUserRequest : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *email;


@property (nonatomic, copy) NSString *first_name;


@property (nonatomic, copy) NSString *last_name;



@end
