//
//  GetLocationRequest.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 3:22:05 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "id" : "1"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface GetLocationRequest : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *magnetId;



@end
