//
//  LocationResult.m
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:39:41 PM
//  @See Also: http://developer.magnet.com
//
#import "LocationResult.h"


@implementation LocationResult

+ (NSDictionary *)attributeMappings {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
    }];
    [dictionary addEntriesFromDictionary:[super attributeMappings]];
    return [dictionary copy];
}

+ (NSDictionary *)listAttributeTypes {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
    }];
    [dictionary addEntriesFromDictionary:[super listAttributeTypes]];
    return [dictionary copy];
}

@end