//
//  LocationResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 3:22:05 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "y" : 3,
  "z" : 4,
  "x" : 2,
  "m" : 5
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface LocationResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, assign) int m;


@property (nonatomic, assign) int x;


@property (nonatomic, assign) int y;


@property (nonatomic, assign) int z;



@end
