//
//  SetLocationRequest.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:39:41 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "id" : 1,
  "x" : "2.0",
  "y" : "2.0",
  "z" : "2.0",
  "m" : "2.0"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface SetLocationRequest : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *m;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *x;


@property (nonatomic, copy) NSString *y;


@property (nonatomic, copy) NSString *z;



@end
