//
//  SetLocationResult.m
//
//  File generated by Magnet rest2mobile 1.1 - Dec 26, 2014 7:55:31 PM
//  @See Also: http://developer.magnet.com
//
#import "SetLocationResult.h"


@implementation SetLocationResult

+ (NSDictionary *)attributeMappings {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
        @"magnetId" : @"id",
    }];
    [dictionary addEntriesFromDictionary:[super attributeMappings]];
    return [dictionary copy];
}

+ (NSDictionary *)listAttributeTypes {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
    }];
    [dictionary addEntriesFromDictionary:[super listAttributeTypes]];
    return [dictionary copy];
}

@end