//
//  SetLocationResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 3:22:05 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "longlat" : "POINT (2.0 3.0 4.0 5.0)",
  "id" : 1,
  "user_id" : 1,
  "updated_at" : "2014-12-25T14:24:24.019Z",
  "created_at" : "2014-12-25T14:24:24.019Z"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface SetLocationResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *created_at;


@property (nonatomic, copy) NSString *longlat;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *updated_at;


@property (nonatomic, assign) int user_id;



@end
