//
//  UserResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:15:34 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "email" : "joblebre@maca.jp",
  "id" : 1,
  "last_name" : "lebre",
  "updated_at" : "2014-12-25T00:17:48.326Z",
  "first_name" : "job",
  "created_at" : "2014-12-25T00:17:48.326Z"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface UserResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *created_at;


@property (nonatomic, copy) NSString *email;


@property (nonatomic, copy) NSString *first_name;


@property (nonatomic, copy) NSString *last_name;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *updated_at;



@end
