//
//  Location.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 3:22:05 PM
//  @See Also: http://developer.magnet.com
//
#import <Rest2Mobile/Rest2Mobile.h>
@class GetLocationRequest;
@class LocationResult;
@class SetLocationRequest;
@class SetLocationResult;

@protocol LocationProtocol <NSObject>

@optional

/**
 Generated from URL GET http://localhost:3000/api/v1/location/{userID}
 GET api/v1/location/{userID}
 @param userID style:TEMPLATE
 @param body style:PLAIN
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getLocation:(NSString *)userID
                   body:(GetLocationRequest *)body
                success:(void (^)(LocationResult *response))success
                failure:(void (^)(NSError *error))failure;

/**
 Generated from URL POST http://192.168.1.11:3000/api/v1/location
 POST api/v1/location
 @param body style:PLAIN
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)setLocation:(SetLocationRequest *)body
                success:(void (^)(SetLocationResult *response))success
                failure:(void (^)(NSError *error))failure;

@end

@interface Location : MMController<LocationProtocol>

@end
