//
//  User.h
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:15:34 PM
//  @See Also: http://developer.magnet.com
//
#import <Rest2Mobile/Rest2Mobile.h>
@class CreateUserRequest;
@class CreateUserResult;
@class UserResult;

@protocol UserProtocol <NSObject>

@optional

/**
 Generated from URL POST http://localhost:3000/api/v1/users
 POST api/v1/users
 @param body style:PLAIN
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)createUser:(CreateUserRequest *)body
               success:(void (^)(CreateUserResult *response))success
               failure:(void (^)(NSError *error))failure;

/**
 Generated from URL GET http://localhost:3000/api/v1/users/{userID}
 GET api/v1/users/{userID}
 @param userID style:TEMPLATE
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getUser:(NSString *)userID
            success:(void (^)(UserResult *response))success
            failure:(void (^)(NSError *error))failure;

@end

@interface User : MMController<UserProtocol>

@end
