//
//  User.m
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:15:34 PM
//  @See Also: http://developer.magnet.com
//
#import "User.h"

@implementation User

+ (NSDictionary *)metaData {

    NSMutableDictionary *controllerMetaData = [NSMutableDictionary dictionary];

    MMControllerMethod *method;
    //controller schema for interface User

    //controller schema for controller method createUser
    method = [MMControllerMethod new];
    method.name = @"createUser";
    method.path = @"api/v1/users";
    method.baseURL = [NSURL URLWithString:@"http://localhost:3000"];
    method.method = @"POST";
    method.consumes = [NSSet setWithObjects:@"application/json", nil];
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *userCreateUserParams = [NSMutableArray new];
    MMControllerParam *userCreateUserBody = [MMControllerParam new];
    userCreateUserBody.name = @"body";
    userCreateUserBody.style = @"PLAIN";
    userCreateUserBody.type = @"CreateUserRequest *";
    userCreateUserBody.optional = @YES;
    [userCreateUserParams addObject:userCreateUserBody];

    method.parameters = [userCreateUserParams copy];
    method.returnType = @"_bean:CreateUserResult";
    [controllerMetaData setObject:method forKey:@"User:createUser"];

    //controller schema for controller method getUser
    method = [MMControllerMethod new];
    method.name = @"getUser";
    method.path = @"api/v1/users/{userID}";
    method.baseURL = [NSURL URLWithString:@"http://localhost:3000"];
    method.method = @"GET";
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *userGetUserParams = [NSMutableArray new];
    MMControllerParam *userGetUserUserID = [MMControllerParam new];
    userGetUserUserID.name = @"userID";
    userGetUserUserID.style = @"TEMPLATE";
    userGetUserUserID.type = @"NSString *";
    userGetUserUserID.optional = @NO;
    [userGetUserParams addObject:userGetUserUserID];

    method.parameters = [userGetUserParams copy];
    method.returnType = @"_bean:UserResult";
    [controllerMetaData setObject:method forKey:@"User:getUser"];


    return [controllerMetaData copy];
}

@end
