//
//  LocationSpec.m
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 2:39:09 PM
//  @See Also: http://developer.magnet.com
//
#import <Kiwi/Kiwi.h>
#import "Location.h"
#import "GetLocationRequest.h"
#import "SetLocationRequest.h"
#import "SetLocationResult.h"

#define DEFAULT_TEST_TIMEOUT 5.0

SPEC_BEGIN(LocationSpec)

describe(@"Location", ^{

    Location *sut = [[Location alloc] init];


    context(@"when calling getLocation", ^{

        it(@"should invoke", ^{
            // FIXME: Set the expected output
            NSString *output;
            // FIXME: Set the input parameter(s)
            NSString *userID;
            GetLocationRequest *body;

            __block NSString *_response;
            [sut getLocation:userID
                        body:body
                     success:^(NSString *response){
                        _response = response;
                     }
                     failure:^(NSError *error){
                     }];

            // Assert
            [[expectFutureValue(_response) shouldEventuallyBeforeTimingOutAfter(DEFAULT_TEST_TIMEOUT)] equal:output];
        });
    });


    context(@"when calling setLocation", ^{

        it(@"should invoke", ^{
            // FIXME: Set the expected output
            SetLocationResult *output;
            // FIXME: Set the input parameter(s)
            SetLocationRequest *body;

            __block SetLocationResult *_response;
            [sut setLocation:body
                     success:^(SetLocationResult *response){
                        _response = response;
                     }
                     failure:^(NSError *error){
                     }];

            // Assert
            [[expectFutureValue(_response) shouldEventuallyBeforeTimingOutAfter(DEFAULT_TEST_TIMEOUT)] equal:output];
        });
    });


});

SPEC_END
