//
//  UserSpec.m
//
//  File generated by Magnet rest2mobile 1.1 - Dec 25, 2014 12:20:37 AM
//  @See Also: http://developer.magnet.com
//
#import <Kiwi/Kiwi.h>
#import "User.h"
#import "CreateUserRequest.h"
#import "CreateUserResult.h"

#define DEFAULT_TEST_TIMEOUT 5.0

SPEC_BEGIN(UserSpec)

describe(@"User", ^{

    User *sut = [[User alloc] init];


    context(@"when calling createUser", ^{

        it(@"should invoke", ^{
            // FIXME: Set the expected output
            CreateUserResult *output;
            // FIXME: Set the input parameter(s)
            CreateUserRequest *body;

            __block CreateUserResult *_response;
            [sut createUser:body
                    success:^(CreateUserResult *response){
                       _response = response;
                    }
                    failure:^(NSError *error){
                    }];

            // Assert
            [[expectFutureValue(_response) shouldEventuallyBeforeTimingOutAfter(DEFAULT_TEST_TIMEOUT)] equal:output];
        });
    });


});

SPEC_END
